<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-WebApplication2-20160108044733" Class="RepoDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\v11.0;AttachDbFilename=|DataDirectory|\aspnet-WebApplication2-20160108044733.mdf;Initial Catalog=aspnet-WebApplication2-20160108044733;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Repositories" Member="Repositories">
    <Type Name="Repository">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Users" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Files" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tags" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastChangeR" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Repository_File" Member="Files1" ThisKey="Id" OtherKey="Repo" Type="File" />
      <Association Name="AspNetUser_Repository" Member="AspNetUser" ThisKey="Owner" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Age" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Discriminator" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="EMail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_Repository" Member="Repositories" ThisKey="Id" OtherKey="Owner" Type="Repository" />
    </Type>
  </Table>
  <Table Name="dbo.Files" Member="Files">
    <Type Name="File">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Repo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastChange" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Repository_File" Member="Repository" ThisKey="Repo" OtherKey="Id" Type="Repository" IsForeignKey="true" />
    </Type>
  </Table>
</Database>